"""Interactive API documentation.

Serves the hand-written OpenAPI spec at /api/openapi.yaml and a Swagger
UI page at /api/docs that reads it.

The spec is written by hand rather than generated by a decorator library
(flasgger, flask-smorest). For a project you have to explain in an
interview that is the better trade: the file is plain YAML you can read
top to bottom, and the route code stays free of documentation
decorators that obscure what the handler actually does.
"""

from __future__ import annotations

from pathlib import Path

from flask import Blueprint, Response, g, render_template_string

bp = Blueprint("docs", __name__, url_prefix="/api")

SPEC_PATH = Path(__file__).resolve().parent.parent / "openapi.yaml"

# Swagger UI is loaded from a CDN, so this page needs an internet
# connection. The spec itself is served locally and is perfectly readable
# on its own at /api/openapi.yaml if you are offline.
SWAGGER_PAGE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Foresight API</title>
  <!-- Without this the browser falls back to requesting /favicon.ico,
       which does not exist and logs a 404 on every page view. -->
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css">
  <style>
    body { margin: 0; background: #fafafa; }
    .topbar { display: none; }
  </style>
</head>
<body>
  <div id="swagger"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js"></script>
  <!-- This is the only inline script left in the project. Rather than
       weaken the Content-Security-Policy application-wide with
       'unsafe-inline', it carries the per-request nonce the policy
       expects. See backend/security_headers.py. -->
  <script nonce="{{ nonce }}">
    window.onload = () => {
      SwaggerUIBundle({
        url: "{{ spec_url }}",
        dom_id: "#swagger",
        deepLinking: true,
        persistAuthorization: true,
        tryItOutEnabled: true
      });
    };
  </script>
</body>
</html>
"""


@bp.get("/docs")
def swagger_ui():
    """Interactive API explorer."""
    return render_template_string(
        SWAGGER_PAGE,
        spec_url="/api/openapi.yaml",
        nonce=g.get("csp_nonce", ""),
    )


@bp.get("/openapi.yaml")
def openapi_spec():
    """The raw OpenAPI 3 document."""
    if not SPEC_PATH.exists():
        return Response("openapi.yaml not found", status=404, mimetype="text/plain")
    return Response(
        SPEC_PATH.read_text(encoding="utf-8"),
        mimetype="application/yaml",
    )
